# キーボードの設定をカスタマイズする
# 項目は https://zmk.dev/docs/config/... を参照

# スリープモードを使う
CONFIG_ZMK_SLEEP=y
# 15分放置でスリー��
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
# Bluetooth接続を安定化
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# マウスポインターキーを使う（効かなそう？）
# CONFIG_ZMK_POINTING=y

# Bluetooth ステータス設定
CONFIG_ZMK_STATUS_ADVERTISEMENT=y
CONFIG_ZMK_STATUS_ADV_KEYBOARD_NAME="Fish"

# Recommended intervals
CONFIG_ZMK_STATUS_ADV_ACTIVE_INTERVAL_MS=1000
CONFIG_ZMK_STATUS_ADV_IDLE_INTERVAL_MS=30000
CONFIG_ZMK_STATUS_ADV_ACTIVITY_TIMEOUT_MS=5000
